export const GET_ALL_DOGS_REQUEST = 'GET_ALL_DOGS_REQUEST';
export const GET_ALL_DOGS_REQUEST_SUCCESS = 'GET_ALL_DOGS_REQUEST_SUCCESS';
export const GET_ALL_DOGS_REQUEST_FAILURE = 'GET_ALL_DOGS_REQUEST_FAILURE';
